"""Criar tabela de cerveja

Revision ID: f4c712df13fe
Revises: 
Create Date: 2020-10-02 13:15:14.248342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c712df13fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_cerveja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estilo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('teor_alcoolico', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_cerveja')
    # ### end Alembic commands ###
